/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vision;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;

/**
 *
 * @author Adiel
 */
public class canvas extends javax.swing.JPanel {

    /**
     * @return the imgprovider
     */
    public IImageProvider getImgprovider() {
        return imgprovider;
    }

    /**
     * @param imgprovider the imgprovider to set
     */
    public void setImgprovider(IImageProvider imgprovider) {
        this.imgprovider = imgprovider;
    }

    public interface IImageProvider {

        public Image getImage();
    }

    private IImageProvider imgprovider = null;

    /**
     * Creates new form canvas
     */
    public canvas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paint(Graphics g) {
        this.setBackground(Color.WHITE);
        g.fillRect(0, 0, this.getWidth(), this.getHeight());
        if (imgprovider != null) {

            g.drawImage(imgprovider.getImage(), 0, 0, getWidth(), getHeight(),
                    this);
        }

        setOpaque(false);
        super.paint(g);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
